#!/bin/bash

#ENV
req=requirements.txt
echo "Using directory $1"

create_env()
{	
	virtualenv ./env
	if [ -f $req ]; then
		source ./env/bin/activate
		pip install -r $req
	fi

}


create_env

alias='py_custom_install $(pwd) && source $(pwd)/env/bin/activate'
