type: google.api.Service
config_version: 3

name: grpc-oa.endpoints.wave16-joan.cloud.goog

title: gRPC-k8s

apis:
- name: endpoints.Users

usage:
  rules:
  - selector: endpoints.Users.GetUsers
    allow_unregistered_calls: true
  - selector: endpoints.Users.getUser
    allow_unregistered_calls: true
