type: google.api.Service
config_version: 3

name: grpc-k8s.endpoints.sbt-endpoints.cloud.goog

title: gRPC-k8s

apis:
- name: endpoints.Users

usage:
  rules:
  - selector: endpoints.Users.GetUsers
    allow_unregistered_calls: true
