apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-bookstore
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: esp-grpc-bookstore
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-grpc-bookstore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-grpc-bookstore
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1.16.0
        args: [
          "--http2_port=9000",
          "--service=grpc-oa.endpoints.wave16-joan.cloud.goog",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:8080"
        ]
        ports:
          - containerPort: 9000
      - name: bookstore
        image: gcr.io/wave16-joan/grpc-endpoints:v0
        ports:
          - containerPort: 8080
