apiVersion: v1
kind: Service
metadata:
  name: esp-grpc
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: esp-grpc
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-grpc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-grpc
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1.16.0
        args: [
          "--http2_port=9000",
          "--service=grpc-k8s.endpoints.sbt-endpoints.cloud.goog",
          "--rollout_strategy=managed",
          "--backend=grpc://0.0.0.0:8080"
        ]
        ports:
          - containerPort: 9000
      - name: grpc-k8s
        image: gcr.io/sbt-endpoints/grpc-endpoints:v1
        ports:
          - containerPort: 8080
