# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: endpoints.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='endpoints.proto',
  package='endpoints',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x65ndpoints.proto\x12\tendpoints\"\x18\n\x06\x45ntity\x12\x0e\n\x06\x65ntity\x18\x01 \x01(\t\"\x1c\n\x08UserList\x12\x10\n\x08username\x18\x01 \x03(\t\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\" \n\x0cUserReturned\x12\x10\n\x08username\x18\x01 \x01(\t2t\n\x05Users\x12\x34\n\x08GetUsers\x12\x11.endpoints.Entity\x1a\x13.endpoints.UserList\"\x00\x12\x35\n\x07getUser\x12\x0f.endpoints.User\x1a\x17.endpoints.UserReturned\"\x00\x62\x06proto3')
)




_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='endpoints.Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='endpoints.Entity.entity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=54,
)


_USERLIST = _descriptor.Descriptor(
  name='UserList',
  full_name='endpoints.UserList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='endpoints.UserList.username', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=84,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='endpoints.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='endpoints.User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=110,
)


_USERRETURNED = _descriptor.Descriptor(
  name='UserReturned',
  full_name='endpoints.UserReturned',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='endpoints.UserReturned.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['Entity'] = _ENTITY
DESCRIPTOR.message_types_by_name['UserList'] = _USERLIST
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserReturned'] = _USERRETURNED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), dict(
  DESCRIPTOR = _ENTITY,
  __module__ = 'endpoints_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.Entity)
  ))
_sym_db.RegisterMessage(Entity)

UserList = _reflection.GeneratedProtocolMessageType('UserList', (_message.Message,), dict(
  DESCRIPTOR = _USERLIST,
  __module__ = 'endpoints_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.UserList)
  ))
_sym_db.RegisterMessage(UserList)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'endpoints_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.User)
  ))
_sym_db.RegisterMessage(User)

UserReturned = _reflection.GeneratedProtocolMessageType('UserReturned', (_message.Message,), dict(
  DESCRIPTOR = _USERRETURNED,
  __module__ = 'endpoints_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.UserReturned)
  ))
_sym_db.RegisterMessage(UserReturned)



_USERS = _descriptor.ServiceDescriptor(
  name='Users',
  full_name='endpoints.Users',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=146,
  serialized_end=262,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUsers',
    full_name='endpoints.Users.GetUsers',
    index=0,
    containing_service=None,
    input_type=_ENTITY,
    output_type=_USERLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getUser',
    full_name='endpoints.Users.getUser',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_USERRETURNED,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERS)

DESCRIPTOR.services_by_name['Users'] = _USERS

# @@protoc_insertion_point(module_scope)
