apiVersion: v1
kind: Service
metadata:
  name: endpoints-oa-k8s
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: endpoints-oa-k8s
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: endpoints-oa-k8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: endpoints-oa-k8s
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=8081",
          "--backend=0.0.0.0:8080",
          "--service=endpoints-oa-k8s.wave16-joan.appspot.com",
          "--rollout_strategy=managed",
        ]
        ports:
        - containerPort: 8081
      - name: k8s-oa-api
        image: gcr.io/wave16-joan/endpoints-image:v0
        ports:
        - containerPort: 8080

